import { Product, SilverRates, Customer, Invoice, ShopConfig, PurchaseStockIn, KhataTransaction } from './types';

export const initialRates: SilverRates = {
  fineRate999: 96.0,
  sterlingRate925: 89.0,
  utensilRate800: 77.0,
  goldRate916: 7150.0,
  scrapRateBuyback: 81.0,
  lastUpdated: new Date().toISOString(),
};

export const initialShopConfig: ShopConfig = {
  shopName: 'SRI SHUBHAM SILVER JEWELS',
  tagline: 'Pure Silver Ornaments, Pooja Articles & Fine Silverware',
  gstin: '29AABCU9603R1ZM',
  hsnCode: '7113',
  phone: '+91 98765 43210',
  email: 'sales@shubhamsilver.com',
  address: '#42, Car Street, Central Market, City - 560001',
  terms: '1. Goods once sold can be exchanged within 7 days against original invoice. 2. Purity guaranteed as per Hallmark specifications. 3. Silver rates calculated on date of billing.',
};

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'SLV-ANK-925-001',
    name: 'Bridal Traditional Silver Payal (Anklet)',
    category: 'Anklets',
    metalType: 'SILVER',
    description: 'Handcrafted 92.5 sterling silver bridal payal pair with fine bell charms and intricate filigree work.',
    grossWeight: 52.4,
    stoneWeight: 1.2,
    netWeight: 51.2,
    purity: 92.5,
    purityGrade: '925 Sterling',
    purchaseRatePerGram: 72.0,
    wastagePercentage: 3.0,
    makingChargeType: 'PER_GRAM',
    makingChargeValue: 55.0,
    gstPercentage: 3.0,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    stockQuantity: 8,
    minStockAlert: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    sku: 'SLV-RNG-925-002',
    name: 'Floral Solitaire Sterling Silver Ring',
    category: 'Rings',
    metalType: 'SILVER',
    description: 'Contemporary sterling silver daily wear floral ring with rhodium protective polish and cz accents.',
    grossWeight: 4.8,
    stoneWeight: 0.3,
    netWeight: 4.5,
    purity: 92.5,
    purityGrade: '925 Sterling',
    purchaseRatePerGram: 73.0,
    wastagePercentage: 2.0,
    makingChargeType: 'FLAT',
    makingChargeValue: 250.0,
    gstPercentage: 3.0,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
    stockQuantity: 15,
    minStockAlert: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    sku: 'SLV-IDL-999-003',
    name: 'Pure Silver Lakshmi Ganesha Idol (999 Fine)',
    category: 'Idols',
    metalType: 'SILVER',
    description: '99.9% fine silver embossed Lakshmi & Ganesh ji pair for diwali puja and housewarming gifts.',
    grossWeight: 100.0,
    stoneWeight: 0.0,
    netWeight: 100.0,
    purity: 99.9,
    purityGrade: '999 Fine',
    purchaseRatePerGram: 82.0,
    wastagePercentage: 1.0,
    makingChargeType: 'PER_GRAM',
    makingChargeValue: 40.0,
    gstPercentage: 3.0,
    imageUrl: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?w=600&auto=format&fit=crop&q=80',
    stockQuantity: 5,
    minStockAlert: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    sku: 'SLV-CHN-925-004',
    name: 'Classic Men Cuban Link Silver Chain',
    category: 'Chains',
    metalType: 'SILVER',
    description: 'Sturdy 22-inch pure sterling silver 925 cuban link neck chain with lobster lock.',
    grossWeight: 28.6,
    stoneWeight: 0.0,
    netWeight: 28.6,
    purity: 92.5,
    purityGrade: '925 Sterling',
    purchaseRatePerGram: 72.5,
    wastagePercentage: 3.5,
    makingChargeType: 'PER_GRAM',
    makingChargeValue: 45.0,
    gstPercentage: 3.0,
    imageUrl: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=600&auto=format&fit=crop&q=80',
    stockQuantity: 6,
    minStockAlert: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    sku: 'SLV-CON-999-005',
    name: '999 Fine Silver Coin (10 Grams) - Lakshmi Embossed',
    category: 'Coins',
    metalType: 'SILVER',
    description: 'Assay certified 10g 999 fine silver bullion coin in tamper-evident blister packaging.',
    grossWeight: 10.0,
    stoneWeight: 0.0,
    netWeight: 10.0,
    purity: 99.9,
    purityGrade: '999 Fine',
    purchaseRatePerGram: 85.0,
    wastagePercentage: 0.0,
    makingChargeType: 'FLAT',
    makingChargeValue: 80.0,
    gstPercentage: 3.0,
    imageUrl: 'https://images.unsplash.com/photo-1624365169365-27a3c3c72b2d?w=600&auto=format&fit=crop&q=80',
    stockQuantity: 25,
    minStockAlert: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    sku: 'SLV-UTN-800-006',
    name: 'Pooja Silver Diya / Lamp (Pair)',
    category: 'Utensils',
    metalType: 'UTENSIL',
    description: 'Authentic South Indian style silver kuthu vilakku / diya pair for daily prayer rituals.',
    grossWeight: 84.0,
    stoneWeight: 0.0,
    netWeight: 84.0,
    purity: 80.0,
    purityGrade: '800 Utensil',
    purchaseRatePerGram: 64.0,
    wastagePercentage: 4.0,
    makingChargeType: 'PER_GRAM',
    makingChargeValue: 35.0,
    gstPercentage: 3.0,
    imageUrl: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=600&auto=format&fit=crop&q=80',
    stockQuantity: 4,
    minStockAlert: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Rajesh Sharma',
    phone: '9845012345',
    email: 'rajesh.sharma@example.com',
    address: '4th Block, Jayanagar, Bengaluru',
    totalSpend: 14200,
    totalBills: 2,
    advanceBalance: 2000,
    outstandingBalance: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust-2',
    name: 'Priya Sundaram',
    phone: '9876543210',
    email: 'priya.s@example.com',
    address: 'Anna Nagar, Chennai',
    totalSpend: 8450,
    totalBills: 1,
    advanceBalance: 0,
    outstandingBalance: 500, // Due balance
    createdAt: new Date().toISOString(),
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2026-0001',
    invoiceType: 'TAX_INVOICE',
    taxType: 'INTRA_STATE',
    customerId: 'cust-1',
    customerName: 'Rajesh Sharma',
    customerPhone: '9845012345',
    customerAddress: '4th Block, Jayanagar, Bengaluru',
    date: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    subtotal: 7508.8,
    wastageTotal: 136.0,
    makingCharges: 2816.0,
    discount: 200,
    taxableAmount: 7308.8,
    cgst: 109.63,
    sgst: 109.63,
    igst: 0,
    grandTotal: 7528.06,
    paymentMode: 'UPI',
    paymentStatus: 'PAID',
    paidAmount: 7528.06,
    costOfGoodsSold: 4100.0,
    profit: 3208.8,
    notes: 'Thank you for shopping with us!',
    createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    items: [
      {
        productSku: 'SLV-ANK-925-001',
        productName: 'Bridal Traditional Silver Payal (Anklet)',
        quantity: 1,
        grossWeight: 52.4,
        netWeight: 51.2,
        purity: 92.5,
        silverRateApplied: 89.0,
        wastageAmount: 136.0,
        makingCharge: 2816.0,
        totalPrice: 7508.8,
        hsnCode: '7113',
      },
    ],
  },
];

export const initialPurchases: PurchaseStockIn[] = [
  {
    id: 'pur-1',
    vendorName: 'Sri Balaji Silver Refiners',
    date: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    productSku: 'SLV-ANK-925-001',
    productName: 'Bridal Traditional Silver Payal (Anklet)',
    quantity: 10,
    weightGrams: 512.0,
    purity: 92.5,
    purchaseRatePerGram: 72.0,
    totalCost: 36864.0,
    invoiceRef: 'VEND-9021',
    notes: 'Pure 925 Hallmark Certified batch',
  },
];
